tim_data <- read.csv(file.choose(),header = T)
View(tim_data)	
summary(tim_data)	
install.packages("lattice")	
library("lattice")	
dotplot(tim_data$Delivery.Time)	
dotplot(tim_data$Sorting.Time)	
boxplot(tim_data$Delivery.Time)	
boxplot(tim_data$Sorting.Time,horizontal = T)
hist(tim_data$Delivery.Time)	
plot(tim_data$Delivery.Time,tim_data$Sorting.Time)
reg <- lm(Delivery.Time~Sorting.Time,data = tim_data)
View(reg)	
summary(reg)	
confint(reg,level = 0.95)
pred <- predict(reg,interval = "predict")
pred <- as.data.frame(pred)	
View(pred)	
cor(tim_data$Delivery.Time,tim_data$Sorting.Time)
reg1 <- lm(Delivery.Time~log(Sorting.Time),data = tim_data)
summary(reg1)	
reg2 <- lm(log(Delivery.Time)~Sorting.Time,data = tim_data)
summary(reg2)	
