emp_data <- read.csv(file.choose(),header = T)
View(emp_data)	
summary(emp_data)	
install.packages("lattice")	
library("lattice")	
dotplot(emp_data$Salary_hike)	
dotplot(emp_data$Churn_out_rate)	
boxplot(emp_data$Salary_hike)	
boxplot(emp_data$Churn_out_rate,horizontal = T)
hist(emp_data$emp_data)	
plot(emp_data$Salary_hike,emp_data$Churn_out_rate)
reg <- lm(Churn_out_rate~Salary_hike,data = emp_data)
View(reg)	
summary(reg)	
confint(reg,level = 0.95)
pred <- predict(reg,interval = "predict")
pred <- as.data.frame(pred)	
View(pred)	
cor(emp_data$Salary_hike,emp_data$Churn_out_rate)
reg1 <- lm(Churn_out_rate~log(Salary_hike),data = emp_data)
summary(reg1)	
reg2 <- lm(log(Salary_hike)~Churn_out_rate,data = emp_data)
summary(reg2)	
